[project]
name = "projectthree"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "django>=5.1.7",
    "pillow>=11.1.0",
]

[dependency-groups]
dev = []
